### ISSUE TITLE
Request/Reply example

### ISSUE THREAD

**Issue by clintmcmahon** [L3Harris/swim-jumpstart#10]
Are there any plans to include a Request/Reply example in this sample? If not, are you able to provide any guidance on how I could implement this functionality into the swim-jumpstart code?

**Comment by ejauregu** [comment]
Sorry for the late reply. We do not have any current plans to include since SCDS does not support Request/Reply Data Feeds. You can try the looking at the NEMS Jumpstart kit that has an example. You can find it here https://github.com/faa-swim/nesg-jumpstart-kit
